// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import { SocketProvider } from "../context/SocketProvider";
import { ProgressBar } from '@/components/progress-bar';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Next-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProgressBar />
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}